### PR TITLE
Fix compiling when not big endian

### PR DESCRIPTION
**Pull request by haal**
## What changes were proposed in this pull request?

Fix compile issues in libconfluo/confluo/types/byte_string.h

## How was this patch tested?

Compilation works

### CODE REVIEW

**Comment by anuragkh** [comment]
Jenkins, test this please.

**Comment by anuragkh** [comment]
Thanks for the patch, this is a good catch. Currently we don't have a testing framework for big-endian systems. Can you provide details of your build environment? I'll setup a reproducible test environment to match it.

**Comment by haal** [comment]
Actually, I found this error trying to dockerize confluo using alpine:latest base image.
Not sure what are the plans about dockerization but I already have some branches:
* using ubuntu - no code changes needed - [here](https://github.com/haal/confluo/tree/docker-alpine)
* using alpine - some code changes needed because alpine does not use glibc) - [here](https://github.com/haal/confluo/tree/docker-ubuntu)
  * code changes are more a hack, just wanted to have it working

**Comment by anuragkh** [comment]
Thanks; we definitely have dockerization on our roadmap, so this will really help! If you want, you can submit a basic version as a PR, I'd be happy to review and merge it.

**Comment by haal** [comment]
Created #139 and #140

**Comment by anuragkh** [comment]
Thanks! I tested this on the alpine docker, and all the tests pass. Merging it in, thanks for the PR!

**Pull request merged**
